config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :travels do
    collection do
      get :export_csv
  get :map
    end
  end
  resources :records
  resources :records do
    collection do
      post :bulk_create
    end
  end
  resources :devices
  resources :locations
  resources :user_accelerometers
  resources :gyroscopes
  resources :accelerometers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/gyroscope.rb
class Gyroscope < ApplicationRecord
    belongs_to :record
end

app/controllers/gyroscopes_controller.rb
class GyroscopesController < ApplicationController
  before_action :set_gyroscope, only: %i[ show edit update destroy ]

  # GET /gyroscopes or /gyroscopes.json
  def index
    @gyroscopes = Gyroscope.all
  end

  # GET /gyroscopes/1 or /gyroscopes/1.json
  def show
    render json: @gyroscope
  end

  # GET /gyroscopes/new
  def new
    @gyroscope = Gyroscope.new
  end

  # GET /gyroscopes/1/edit
  def edit
  end

  # POST /gyroscopes or /gyroscopes.json
  def create
    @gyroscope = Gyroscope.new(gyroscope_params)

    respond_to do |format|
      if @gyroscope.save
        format.html { redirect_to @gyroscope, notice: "Gyroscope was successfully created." }
        format.json { render :show, status: :created, location: @gyroscope }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gyroscope.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gyroscopes/1 or /gyroscopes/1.json
  def update
    respond_to do |format|
      if @gyroscope.update(gyroscope_params)
        format.html { redirect_to @gyroscope, notice: "Gyroscope was successfully updated." }
        format.json { render :show, status: :ok, location: @gyroscope }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gyroscope.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gyroscopes/1 or /gyroscopes/1.json
  def destroy
    @gyroscope.destroy!

    respond_to do |format|
      format.html { redirect_to gyroscopes_path, status: :see_other, notice: "Gyroscope was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gyroscope
      @gyroscope = Gyroscope.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def gyroscope_params
      params.expect(gyroscope: [ :x, :y, :z ])
    end
end

app/helpers/gyroscopes_helper.rb
module GyroscopesHelper
end

app/views/gyroscopes/_form.html.erb
<%= form_with(model: gyroscope) do |form| %>
  <% if gyroscope.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(gyroscope.errors.count, "error") %> prohibited this gyroscope from being saved:</h2>

      <ul>
        <% gyroscope.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :x, style: "display: block" %>
    <%= form.text_field :x %>
  </div>

  <div>
    <%= form.label :y, style: "display: block" %>
    <%= form.text_field :y %>
  </div>

  <div>
    <%= form.label :z, style: "display: block" %>
    <%= form.text_field :z %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/gyroscopes/_gyroscope.html.erb
<div id="<%= dom_id gyroscope %>">
  <p>
    <strong>X:</strong>
    <%= gyroscope.x %>
  </p>

  <p>
    <strong>Y:</strong>
    <%= gyroscope.y %>
  </p>

  <p>
    <strong>Z:</strong>
    <%= gyroscope.z %>
  </p>

</div>

app/views/gyroscopes/edit.html.erb
<% content_for :title, "Editing gyroscope" %>

<h1>Editing gyroscope</h1>

<%= render "form", gyroscope: @gyroscope %>

<br>

<div>
  <%= link_to "Show this gyroscope", @gyroscope %> |
  <%= link_to "Back to gyroscopes", gyroscopes_path %>
</div>

app/views/gyroscopes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Gyroscopes" %>

<h1>Gyroscopes</h1>

<div id="gyroscopes">
  <% @gyroscopes.each do |gyroscope| %>
    <%= render gyroscope %>
    <p>
      <%= link_to "Show this gyroscope", gyroscope %>
    </p>
  <% end %>
</div>

<%= link_to "New gyroscope", new_gyroscope_path %>

app/views/gyroscopes/new.html.erb
<% content_for :title, "New gyroscope" %>

<h1>New gyroscope</h1>

<%= render "form", gyroscope: @gyroscope %>

<br>

<div>
  <%= link_to "Back to gyroscopes", gyroscopes_path %>
</div>

app/views/gyroscopes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @gyroscope %>

<div>
  <%= link_to "Edit this gyroscope", edit_gyroscope_path(@gyroscope) %> |
  <%= link_to "Back to gyroscopes", gyroscopes_path %>

  <%= button_to "Destroy this gyroscope", @gyroscope, method: :delete %>
</div>