config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :travels do
    collection do
      get :export_csv
  get :map
    end
  end
  resources :records
  resources :records do
    collection do
      post :bulk_create
    end
  end
  resources :devices
  resources :locations
  resources :user_accelerometers
  resources :gyroscopes
  resources :accelerometers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/accelerometer.rb
class Accelerometer < ApplicationRecord
    belongs_to :record
end

app/controllers/accelerometers_controller.rb
class AccelerometersController < ApplicationController
  before_action :set_accelerometer, only: %i[ show edit update destroy ]

  # GET /accelerometers or /accelerometers.json
  def index
    @accelerometers = Accelerometer.all
  end

  # GET /accelerometers/1 or /accelerometers/1.json
  def show
    render json: @accelerometer
  end

  # GET /accelerometers/new
  def new
    @accelerometer = Accelerometer.new
  end

  # GET /accelerometers/1/edit
  def edit
  end

  # POST /accelerometers or /accelerometers.json
  def create
    @accelerometer = Accelerometer.new(accelerometer_params)

    respond_to do |format|
      if @accelerometer.save
        format.html { redirect_to @accelerometer, notice: "Accelerometer was successfully created." }
        format.json { render :show, status: :created, location: @accelerometer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @accelerometer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accelerometers/1 or /accelerometers/1.json
  def update
    respond_to do |format|
      if @accelerometer.update(accelerometer_params)
        format.html { redirect_to @accelerometer, notice: "Accelerometer was successfully updated." }
        format.json { render :show, status: :ok, location: @accelerometer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @accelerometer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accelerometers/1 or /accelerometers/1.json
  def destroy
    @accelerometer.destroy!

    respond_to do |format|
      format.html { redirect_to accelerometers_path, status: :see_other, notice: "Accelerometer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accelerometer
      @accelerometer = Accelerometer.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def accelerometer_params
      params.expect(accelerometer: [ :x, :y, :z ])
    end
end

app/helpers/accelerometers_helper.rb
module AccelerometersHelper
end

app/views/accelerometers/_accelerometer.html.erb
<div id="<%= dom_id accelerometer %>">
  <p>
    <strong>X:</strong>
    <%= accelerometer.x %>
  </p>

  <p>
    <strong>Y:</strong>
    <%= accelerometer.y %>
  </p>

  <p>
    <strong>Z:</strong>
    <%= accelerometer.z %>
  </p>

</div>

app/views/accelerometers/_form.html.erb
<%= form_with(model: accelerometer) do |form| %>
  <% if accelerometer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(accelerometer.errors.count, "error") %> prohibited this accelerometer from being saved:</h2>

      <ul>
        <% accelerometer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :x, style: "display: block" %>
    <%= form.text_field :x %>
  </div>

  <div>
    <%= form.label :y, style: "display: block" %>
    <%= form.text_field :y %>
  </div>

  <div>
    <%= form.label :z, style: "display: block" %>
    <%= form.text_field :z %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/accelerometers/edit.html.erb
<% content_for :title, "Editing accelerometer" %>

<h1>Editing accelerometer</h1>

<%= render "form", accelerometer: @accelerometer %>

<br>

<div>
  <%= link_to "Show this accelerometer", @accelerometer %> |
  <%= link_to "Back to accelerometers", accelerometers_path %>
</div>

app/views/accelerometers/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Accelerometers" %>

<h1>Accelerometers</h1>

<div id="accelerometers">
  <% @accelerometers.each do |accelerometer| %>
    <%= render accelerometer %>
    <p>
      <%= link_to "Show this accelerometer", accelerometer %>
    </p>
  <% end %>
</div>

<%= link_to "New accelerometer", new_accelerometer_path %>

app/views/accelerometers/new.html.erb
<% content_for :title, "New accelerometer" %>

<h1>New accelerometer</h1>

<%= render "form", accelerometer: @accelerometer %>

<br>

<div>
  <%= link_to "Back to accelerometers", accelerometers_path %>
</div>

app/views/accelerometers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @accelerometer %>

<div>
  <%= link_to "Edit this accelerometer", edit_accelerometer_path(@accelerometer) %> |
  <%= link_to "Back to accelerometers", accelerometers_path %>

  <%= button_to "Destroy this accelerometer", @accelerometer, method: :delete %>
</div>