config/routes.rb
Rails.application.routes.draw do
  resources :ratings
  resources :travels do
    collection do
      get :export_csv
  get :map
    end
  end
  resources :records
  resources :records do
    collection do
      post :bulk_create
    end
  end
  resources :devices
  resources :locations
  resources :user_accelerometers
  resources :gyroscopes
  resources :accelerometers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/rating.rb
class Rating < ApplicationRecord
   belongs_to :record
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: %i[ show edit update destroy ]

  # GET /ratings or /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1 or /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings or /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: "Rating was successfully created." }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1 or /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: "Rating was successfully updated." }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1 or /ratings/1.json
  def destroy
    @rating.destroy!

    respond_to do |format|
      format.html { redirect_to ratings_path, status: :see_other, notice: "Rating was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def rating_params
      params.expect(rating: [ :value ])
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_with(model: rating) do |form| %>
  <% if rating.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
        <% rating.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.number_field :value %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ratings/_rating.html.erb
<div id="<%= dom_id rating %>">
  <p>
    <strong>Value:</strong>
    <%= rating.value %>
  </p>

</div>

app/views/ratings/edit.html.erb
<% content_for :title, "Editing rating" %>

<h1>Editing rating</h1>

<%= render "form", rating: @rating %>

<br>

<div>
  <%= link_to "Show this rating", @rating %> |
  <%= link_to "Back to ratings", ratings_path %>
</div>

app/views/ratings/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Ratings" %>

<h1>Ratings</h1>

<div id="ratings">
  <% @ratings.each do |rating| %>
    <%= render rating %>
    <p>
      <%= link_to "Show this rating", rating %>
    </p>
  <% end %>
</div>

<%= link_to "New rating", new_rating_path %>

app/views/ratings/new.html.erb
<% content_for :title, "New rating" %>

<h1>New rating</h1>

<%= render "form", rating: @rating %>

<br>

<div>
  <%= link_to "Back to ratings", ratings_path %>
</div>

app/views/ratings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rating %>

<div>
  <%= link_to "Edit this rating", edit_rating_path(@rating) %> |
  <%= link_to "Back to ratings", ratings_path %>

  <%= button_to "Destroy this rating", @rating, method: :delete %>
</div>